config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# settings.py 를 직접 import 하는 게 아니라 장고 시스템에서 conf 에 clone 된 settings 를 import.


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # DEBUG 가 켜져있을 때 (developing 일 때)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# MEDIA_URL 로 접근했을 때 어느 경로를 참조할 것인지

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
    path("my-list/", views.MyReservationsView.as_view(), name="my-list"),
    path(
        "room-reservation/<int:room_pk>/",
        views.RoomReservationView.as_view(),
        name="room-reservation",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("sign-up/", views.SignUpView.as_view(), name="sign-up"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-avatar/", views.UpdateAvatarView.as_view(), name="update-avatar"),
    path("update-avatar-done/", views.update_avatar_done, name="update-avatar-done"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    # path("switch_hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_lang, name="switch-language"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center  mt-14 text-gray-500 font-medium">
    <span>&copy; H A N U M</span>
    <div class="my-3 flex justify-end">
        {% get_current_language as LANGUAGE_CODE %}
        <select class="w-24 h-8" id="js-lang">
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %} selected {% endif %}>한국어</option>
            <option value="en" {% if LANGUAGE_CODE == 'en' %} selected {% endif %}>English</option>
        </select>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class=" absolute mx-auto left-0 right-0 top-0 flex justify-center h-1">
    {% for message in messages %}
    <li
        class="font-light text-yellow-900 rounded-full z-10 bg-gray-100 py-6 flex items-center px-20 message {% if message.tags %} {{ message.tags }} {% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium font-mono	">

    {% if user.is_authenticated %}

    <li class="nav_link">
        <a href="{% url 'lists:see-favs' %}">Favs.</a>
    <li class="nav_link">
        <a href="{% url 'reservations:my-list' %}">Reservation</a>
    <li class="nav_link">
        <a href="{% url 'users:profile' user.pk%}">Profile</a>
    </li>
    <li class="nav_link mr-3">
        <a href="{% url 'users:logout' %}">LogOut</a>
    </li>

    {% else %}

    <li class="nav_link">
        <a href="{% url 'users:login' %}">Log in</a>
    </li>
    <li class="nav_link mr-3">
        <a href="{% url 'users:sign-up' %}">Sign
            up</a>
    </li>

    {% endif %}

</ul>

templates/partials/social_login.html
<div class="w-full flex items-center justify-center">
    <a href="{%url 'users:github-login'%}"
        class="w-2/3 border-2 bg-gray-400 border-white text-center rounded-md p-5 flex items-center justify-center font-medium mr-2">
        <i class="fab fa-github mr-2"></i>Github 로 계속하기
    </a>
    <a href="{%url 'users:kakao-login'%}"
        class="w-2/3 border-2 bg-yellow-300 border-white text-center rounded-md p-5 text-yellow-900 flex items-center justify-center font-medium ml-2">
        <i class="fas fa-comment mr-2"></i>Kakao로 계속하기
    </a>
</div>
<div class="flex items-center w-full py-3">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-light px-5">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>