config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# settings.py 를 직접 import 하는 게 아니라 장고 시스템에서 conf 에 clone 된 settings 를 import.


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # DEBUG 가 켜져있을 때 (developing 일 때)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# MEDIA_URL 로 접근했을 때 어느 경로를 참조할 것인지

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
    path("my-list/", views.MyReservationsView.as_view(), name="my-list"),
    path(
        "room-reservation/<int:room_pk>/",
        views.RoomReservationView.as_view(),
        name="room-reservation",
    ),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),  # pk 라는 이름 부여해준것.
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.UploadPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="del-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere", required=False)
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        queryset=models.RoomType.objects.all(), required=False, empty_label="Any Kind"
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("file", "caption")

    def save(self, pk, *args, **kwargs):  # View 에서 넘어온 인자 pk.

        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateRoomForm, self).__init__(*args, **kwargs)
        self.fields["check_in"].widget.attrs["placeholder"] = "00:00"
        self.fields["check_out"].widget.attrs["placeholder"] = "00:00"

    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
# from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, UpdateView, FormView, View
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from users import mixins as user_mixins
from . import models, forms, mixins


# from django.http import Http404
# from django.core.paginator import Paginator, EmptyPage
# from django.utils import timezone
# from django_countries import countries


# 수동으로 pagination 만들기
# def all_rooms(request):
#     page = request.GET.get("page", 1)
#     page = int(page or 1)  # /?page=  url 에 이렇게 입력했을 땐 값이 없어서 오류가 난다. get 기본값과는 다름.
#     page_size = 10
#     limit = page_size * page
#     offset = limit - page_size
#     all_rooms = models.Room.objects.all()[offset:limit]
#     page_count = ceil(models.Room.objects.count() / page_size)
#     return render(
#         request,
#         "rooms/home.html",
#         context={
#             "rooms": all_rooms,
#             "page": page,
#             "page_count": page_count,
#             "page_range": range(1, page_count + 1),
#         },
#     )

# Function Based View FBV
# def all_rooms(request):
#     page = request.GET.get("page", 1)
#     room_list = models.Room.objects.all()
#     # 지금이 아닌 room_list 가 호출됐을 때 query set 을 불러온다. DataBase 가 방대할 때는 치명적일 수 있으니 조심.
#     paginator = Paginator(room_list, 10, orphans=5)  # 자투리 다섯개까지는 마지막 페이지로 밀어넣기
#     # rooms = paginator.get_page(page)  # 10 단위로 쪼갰을 때 get 으로 얻은 page 에 해당하는 page 객체.
#     try:
#         rooms = paginator.page(int(page))

#         return render(request, "rooms/home.html", context={"page": rooms})

#     except EmptyPage:
#         return redirect("/")


class HomeView(ListView):  # Class Based View

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


# Function Based View

# def room_detail(request, pk):

#     try:
#         room = models.Room.objects.get(pk=pk)

#         return render(request, "rooms/detail.html", context={"room": room})

#     except models.Room.DoesNotExist:

#         # return redirect(reverse("core:home"))  # home 으로 redirect
#         raise Http404()
#         # 404 page 를 이용하면 브라우저에게도 아무것도 찾지 못했다는 걸 알려주고 저장하지 않을 수 있다.


class RoomDetail(DetailView):

    """ Room Detail Definition """

    model = models.Room


# ## Create Search View Manually
# def search(request):
#     city = request.GET.get("city", "")
#     city = str.capitalize(city)
#     country = request.GET.get("country", "KR")
#     room_type = int(request.GET.get("room_type", 0))
#     price = int(request.GET.get("price", 0))
#     guests = int(request.GET.get("guests", 0))
#     bedrooms = int(request.GET.get("bedrooms", 0))
#     beds = int(request.GET.get("beds", 0))
#     baths = int(request.GET.get("baths", 0))
#     instant = bool(request.GET.get("instant", False))
#     superhost = bool(request.GET.get("superhost", False))
#     s_amenities = request.GET.getlist("amenities")
#     s_facilities = request.GET.getlist("facilities")

#     form = {
#         "city": city,
#         "s_country": country,
#         "s_room_type": room_type,
#         "price": price,
#         "guests": guests,
#         "bedrooms": bedrooms,
#         "beds": beds,
#         "baths": baths,
#         "s_amenities": s_amenities,
#         "s_facilities": s_facilities,
#         "instant": instant,
#         "superhost": superhost,
#     }

#     room_types = models.RoomType.objects.all()
#     amenities = models.Amenity.objects.all()
#     facilities = models.Facility.objects.all()

#     choices = {
#         "countries": countries,
#         "room_types": room_types,
#         "amenities": amenities,
#         "facilities": facilities,
#     }

#     filter_args = {}

#     if city != "":
#         filter_args["city__startswith"] = city

#     filter_args["country"] = country

#     if room_type != 0:
#         filter_args["room_type__pk"] = room_type

#     if price != 0:
#         filter_args["price__lte"] = price  # less than equal

#     if guests != 0:
#         filter_args["guests__gte"] = guests

#     if bedrooms != 0:
#         filter_args["bedrooms__gte"] = bedrooms

#     if beds != 0:
#         filter_args["bed_s_gte"] = beds

#     if baths != 0:
#         filter_args["baths__gte"] = baths

#     if instant is True:
#         filter_args["instant_book"] = True

#     if superhost is True:
#         filter_args["host__superhost"] = True

#     rooms = models.Room.objects.filter(**filter_args)

#     if len(s_amenities) > 0:
#         for s_amenity in s_amenities:
#             rooms = rooms.filter(amenities__pk=int(s_amenity))

#     if len(s_facilities) > 0:
#         for s_facility in s_facilities:
#             rooms = rooms.filter(facilities__pk=s_facility)

#     return render(
#         request,
#         "rooms/search.html",
#         context={**form, **choices, "rooms": rooms},  # dict 합칠 때 unpack
#     )


class SearchView(View):
    def get(self, request):

        country = request.GET.get("country")
        city = request.GET.get("city")
        if country:
            form = forms.SearchForm(request.GET)
            # request.GET 을 통해 변수 form 에 html form 을 통해서 넘어온 정보가 저장됨.
            if form.is_valid():

                country = form.cleaned_data.get("country")
                city = form.cleaned_data.get("city")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                beds = form.cleaned_data.get("beds")
                bedrooms = form.cleaned_data.get("bedrooms")
                baths = form.cleaned_data.get("baths")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")

                filter_args = {}

                if city != "Anywhere" and city != "":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price  # less than equal

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                rooms = models.Room.objects.filter(**filter_args)

                for amenity in amenities:
                    rooms = rooms.filter(amenities=amenity)

                for facility in facilities:
                    rooms = rooms.filter(facilities=facility)

                # paginator = Paginator(qs, 10, orphans=5)

                # page = request.GET.get("page", 1)
                # rooms = paginator.get_page(page)

        else:
            form = forms.SearchForm()
            rooms = models.Room.objects.filter(city__startswith=city)
            # return render(request, "rooms/search.html", context={"form": form})

        return render(
            request, "rooms/search.html", context={"form": form, "rooms": rooms}
        )


class EditRoomView(mixins.RoomHostOnlyView, user_mixins.LoggedInOnlyView, UpdateView):

    """ Edit Room View Description """

    model = models.Room
    template_name = "rooms/room_edit.html"

    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_success_url(self):
        messages.warning(self.request, "변경 완료!")
        return super().get_success_url()


class RoomPhotosView(mixins.RoomHostOnlyView, user_mixins.LoggedInOnlyView, DetailView):

    """ Room Photos View Description """

    model = models.Room
    template_name = "rooms/room_photos.html"


@login_required
def delete_photo(request, room_pk, photo_pk):

    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host == request.user:
            photo = models.Photo.objects.get(pk=photo_pk)
            photo.delete()
            messages.error(request, "삭제되었습니다")
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))

    return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))


class EditPhotoView(mixins.PhotoHostOnlyView, user_mixins.LoggedInOnlyView, UpdateView):

    """ Edit Photo View Description """

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)

    def get_object(self, queryset=None):

        photo = get_object_or_404(models.Photo, pk=self.kwargs.get("photo_pk"))

        return photo

    def get_success_url(self):
        room_pk = int(self.kwargs.get("room_pk"))
        messages.warning(self.request, "변경 완료!")

        return reverse("rooms:photos", kwargs={"pk": room_pk})


class UploadPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/upload_photo.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load is_booked i18n on_favs %}

{% block page_title %}
{{room.name}}
{% endblock page_title %}


{% block content %}
<div class="-mt-5 container max-w-full h-75vh mb-20 flex">
    <div class="h-full w-1/2 bg-cover bg-center" style="background-image: url({{room.first_photo}});"></div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_photos %}
        <div style="background-image: url({{photo.file.url}});" class="  w-1/2 h-auto bg-cover bg-center"></div>
        {% endfor %}
    </div>
</div>
<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between">
            <div>
                <h4 class="text-3xl font-semibold mb-4">{{room.name}}</h4>
                <span class="text-lg font-light text-gray-600">{{room.city}}</span>
            </div>

            {% if user == room.host %}
            <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                <div class="flex flex-col justify-center items-center">
                    {% include 'mixins/link_removed_user_avatar.html' with user_obj=room.host %}
                    <span class="mt-2 font-light text-gray-500">{{room.host.first_name}}</span>
                </div>
            </a>
            {% else %}
            <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                <div class="flex flex-col items-center justify-center">
                    {% include 'mixins/user_avatar.html' with user_obj=room.host %}
                    <span class="mt-2 font-light text-gray-500">{{room.host.first_name}}</span>
                </div>
            </a>

            {% endif %}
        </div>
        <div class="flex border-section mt-3 flex-col">
            <div>
                <span class="mr-4 font-medium text-gray-700">{{room.room_type}}</span>
                <span class="mr-3 font-medium text-gray-700">침대 {{room.beds}} 개 |</span>
                <span class="mr-3 font-medium text-gray-700">방 {{room.bedrooms}} 개 |</span>
                <span class="mr-3 font-medium text-gray-700">화장실 {{room.baths}} 개 |</span>
                <span class="mr-3 font-medium text-gray-700">게스트 {{room.guests}} 명</span>
            </div>
            {% if room.host != user %}
            {% on_favs room as on_favs_boolean %}
            {% if on_favs_boolean %}
            <div class="mt-8 bg-green-600 rounded-lg w-1/3">
                <a class="btn text-gray-200 font-light h-10" href="{% url 'lists:toggle-room' room.pk %}?action=remove">
                    {% trans 'Remove from Favorites' %}
                </a>
            </div>
            {% else %}
            <div class="mt-8 bg-blue-400 rounded-lg w-1/3">
                <a class="btn text-gray-100 font-light h-10" href="{% url 'lists:toggle-room' room.pk %}?action=add">
                    {% trans 'Save to Favorites' %}
                </a>
            </div>
            {% endif %}
            {% endif %}
        </div>
        <p class="border-section text-sm">{{room.description}}</p>
        <div class="border-section">
            <div>
                <h4 class="text-xl mb-7">편의시설</h4>
                {% for a in room.amenities.all %}
                <li class="mb-2 font-light">{{a}}</li>
                {% endfor %}
            </div>
        </div>
        {% if room.facilities.all %}
        <div class="border-section">
            <div>
                <h4 class="text-xl mb-7">기타</h4>
                {% for f in room.facilities.all %}
                <li class="mb-2 font-light">{{f}}</li>
                {% endfor %}
            </div>
        </div>
        {%endif%}
        {% if room.house_rules.all %}
        <div class="border-section">
            <div>
                <h4 class="text-xl mb-7">이용 시 주의사항</h4>
                {% for r in room.house_rules.all %}
                <li class="mb-2 font-light">{{r}}</li>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="mt-10">
            <div>
                <h4 class="text-3xl font-light mb-7">방문자 리뷰</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-green-500"></i>
                        <span class="text-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-4"></div>
                    <div>
                        <span>{{room.reviews.count}} 개의 리뷰</span>
                    </div>
                </div>
                <div class="mt-16">
                    {% for r in room.reviews.all %}
                    <div class='border-section'>
                        <div class="mb-3 flex">
                            <div>
                                {% include 'mixins/user_avatar.html' with user_obj=r.user h_and_w='w-10 h-10' %}

                            </div>
                            <div class="flex flex-col ml-5">
                                <span class="mb-1">{{r.user.first_name}}</span>
                                <span class="text-sm text-gray-500">{{r.created}}</span>
                            </div>
                        </div>
                        <p>{{r.review}}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="w-1/3 flex flex-col items-center">

        {% if room.host == user %}
        <a href="{% url 'reservations:room-reservation' room.pk %}"
            class="btn bg-blue-300 hover:bg-blue-400 hover:text-gray-100 transition-all duration-500 ease-in-out w-full mb-4">예약
            확인</a>
        <a href="{% url 'rooms:edit' room.pk %}"
            class="btn bg-gray-300 hover:bg-blue-400 hover:text-gray-100 transition-all duration-500 ease-in-out w-full ">수정하기</a>
        {% else %}
        {% for index, calendar in room.get_calendars %}
        <div class="mb-20 w-4/5">
            <span class="block mb-8 text-center font-semibold text-lg">{{calendar.month}} / {{calendar.year}}</span>
            <div class="cal-grid mb-4">
                {% for day in calendar.day_names %}
                <span class="mb-4">{{day}}</span>
                {% endfor %}
            </div>
            <div class="cal-grid font-light text-gray-500">
                {% for day in calendar.get_days %}
                {% is_booked room day as is_booked_bool%}
                {% if day.number != 0 %}
                {% if day.past and index == 0 %}
                <span class="bg-gray-300 w-full text-center font-light rounded text-gray-200 p-1">{{day}}</span>
                {% elif is_booked_bool%}
                <span
                    class="bg-gray-300 w-full text-center font-light rounded text-red-700 p-1 line-through">{{day}}</span>
                {% else %}
                <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}"
                    class="bg-gray-300 w-full text-center font-light rounded text-gray-700 p-1 hover:bg-blue-300 hover:text-white cursor-pointer">{{day}}</a>
                {% endif %}
                {% else %}
                <span></span>
                {% endif %}
                {% endfor %}

            </div>

        </div>
        {% endfor %}

        {% endif %}
    </div>
</div>
{% endblock %}

templates/rooms/room_list.html
{% extends 'base.html' %}
{% load static %}



{% block page_title %}
HOME
{% endblock page_title %}


{% block content %}

<div class="container mx-auto">

    <div class="mx-auto bg-gray-800 h-50vh w-11/12 mt-40 rounded-xl bg-cover bg-center "
        style="background-image: url({% static 'img/home_banner.jpg' %})">
        <a href="{% url 'rooms:create' %}" class="flex justify-center items-center h-full w-full container mx-auto">
            <span class="whitespace-nowrap text-banner font-light text-purple-300">숙소 등록하기</span>
        </a>
    </div>

    <div class="flex flex-wrap mt-16">
        {% for room in rooms %}
        {% include 'mixins/room_card.html' with room=room %}
        {% endfor %}
    </div>

    <div class="flex items-center mx-auto container justify-center mt-16">
        {% if page_obj.has_previous %}
        <a href=?page={{page_obj.previous_page_number}} class="hover:text-yellow-500"><i
                class="fas fa-chevron-left"></i>

        </a>
        {% endif %}

        <span class="mx-3">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

        {% if page_obj.has_next %}
        <a href=?page={{page_obj.next_page_number}} class="hover:text-yellow-500"><i class="fas fa-chevron-right"></i>

        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}


{% block page_title %}
{{room.name}}'s Photos
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}


{% block content %}
<div class="container mx-auto my-40 flex flex-col items-center">
    <span class="flex w-full justify-center text-blue-600 text-5xl font-light mb-16">사진</span>
    {% for photo in room.photos.all %}
    <div class="mb-7 border-white border-4 p-6 rounded-lg w-1/2 flex justify-between">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-auto h-32">
            <span class="ml-5 mt-5">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col">
            <a class="whitespace-nowrap btn text-2xl font-light text-gray-800"
                href="{% url 'rooms:edit-photo' room.pk photo.pk %}">수정</a>
            <a class="whitespace-nowrap btn text-2xl font-light text-red-500"
                href="{% url 'rooms:del-photo' room.pk photo.pk %}">삭제</a>
        </div>
    </div>
    {% endfor %}
    <a class="btn border-4 text-gray-800 font-light text-xl bg-green-300 border-white w-1/2"
        href="{% url 'rooms:add-photo' room.pk %}">
        사진 추가하기</a>
    <a class="btn mt-4 border-4 text-gray-600 font-light text-xl bg-gray-100 border-white hover:bg-blue-300 hover:text-white transition duration-500 ease-in-out w-1/2"
        href="{% url 'rooms:edit' room.pk %}">
        돌아가기
    </a>


</div>
{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
Search
{% endblock page_title %}


{% block search_bar %}
{% endblock search_bar %}


{% block content %}
<h2>Search!</h2>

<form method='get' action="{% url 'rooms:search'%}">
    {{form.as_p}}
    <button>Search</button>
</form>


<h3>Results</h3>

{% for room in rooms %}
<h3>{{room.name}}</h3>
{% endfor %}

{% endblock content %}

templates/rooms/search_all_manually.html
{% extends 'base.html' %}


{% block page_title %}
Search
{% endblock page_title %}


{% block search_bar %}
{% endblock search_bar %}


{% block content %}
<h2>Search!</h2>
<form method="get" action="{% url 'rooms:search' %}">
    <div>
        <label for="city">City</label>
        <input value='{{city}}' id='city' name='city' placeholder="Search by City">
    </div>

    <div>
        <label for="country">Country</label>
        <select id="country" name="country">

            {% for country in countries%}
            <option value="{{country.code}}" {% if country.code == s_country %}selected{%endif%}>{{country.name}}</option>
            {% endfor %}

        </select>
    </div>
    <div>
        <label for="room_type">Room Types</label>
        <select id="room_type" name="room_type">
            <option value="0" {%if s_room_type == 0%}selected{%endif%}>Any kind</option>
            {% for room_type in room_types %}
            <option value="{{room_type.pk}}" {%if s_room_type == room_type.pk%}selected{%endif%}>{{room_type.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="price">Price</label>
        <input value = {{price}} type="number" name="price" id="price" placeholder="Price">
    </div>
    <div>
        <label for="guests">Guests</label>
        <input value = {{guests}} type="number" name="guests" id="guests" placeholder="Guests">
    </div>
    <div>
        <label for="bedrooms">Bedrooms</label>
        <input value = {{bedrooms}} type="number" name="bedrooms" id="bedrooms" placeholder="Bedrooms">
    </div>
    <div>
        <label for="beds">Beds</label>
        <input value = {{beds}} type="number" name="beds" id="beds" placeholder="Beds">
    </div>
    <div>
        <label for="baths">Baths</label>
        <input value = {{baths}} type="number" name="baths" id="baths" placeholder="Baths">
    </div>
    <div>
        <label for="instant">Instant Book Only?</label>
        <input type="checkbox" name="instant" id="instant" {% if instant %}checked{% endif %}>
    </div>
    <div>
        <label for="superhost">By Superhost Only?</label>
        <input type="checkbox" name="superhost" id="superhost" {% if superhost %}checked{% endif %}>
    </div>
    <div>
        <h3>Amenities</h3>
        <ul>
            
            {% for a in amenities %}
                <li>
                    <label for="a_{{a.pk}}">{{a.name}}</label>
                    <input 
                    name="amenities" 
                    id="a_{{a.pk}}" 
                    type="checkbox" 
                    value={{a.pk}}
                    {%if a.pk|slugify in s_amenities%}  
                        checked
                    {%endif%}>
                </li>
            {% endfor %}
                
        </ul>
    </div>
    <div>
        <h3>Facilities</h3>
        <ul>
            
            {% for f in facilities %}
                <li>
                    <label for="f_{{f.pk}}">{{f.name}}</label>
                    <input 
                        name="facilities" 
                        id="f_{{f.pk}}" 
                        type="checkbox" 
                        value={{f.pk}}
                        {%if f.pk|slugify in s_facilities%}  
                            checked
                        {%endif%}
                    >
                </li>
            {% endfor %}
                
        </ul>
    </div>


    <button>Search</button>
</form>

<h3>Results</h3>

{% for room in rooms %}
    <h3>{{room.name}}</h3>
{% endfor %}
    
{% endblock content%}