config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# settings.py 를 직접 import 하는 게 아니라 장고 시스템에서 conf 에 clone 된 settings 를 import.


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # DEBUG 가 켜져있을 때 (developing 일 때)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# MEDIA_URL 로 접근했을 때 어느 경로를 참조할 것인지

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),  # pk 라는 이름 부여해준것.
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.UploadPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="del-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("sign-up/", views.SignUpView.as_view(), name="sign-up"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-avatar/", views.UpdateAvatarView.as_view(), name="update-avatar"),
    path("update-avatar-done/", views.update_avatar_done, name="update-avatar-done"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    # path("switch_hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_lang, name="switch-language"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block page_title %}{% endblock page_title %} | &copy; HANUM
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static  'css/styles.css' %}">
</head>

<body class="text-gray-800 font-mono mt-24 bg-gray-200">
    <header
        class="inset-0 container max-w-full flex items-center justify-between pr-6 pl-4 h-20 border-b-4 border-white fixed bg-yellow-400">
        {% include 'partials/messages.html' %}
        <div class="flex items-center w-3/5">
            <a href="{% url 'core:home' %}" class="mr-6">
                <img class="w-10" src="{%static 'img/beerb_logo.png' %}">
            </a>

            {% block search_bar %}
            <form method="get" action="{% url 'rooms:search' %}" class="w-full flex items-center">
                <input
                    class="mt-3 search-box border px-5 text-sm font-medium py-2.5 rounded-lg w-2/5 shadow-y-md hover:shadow-y-lg focus:outline-none placeholder-gray-600"
                    name='city' placeholder="{% trans 'Search by City' %}">
            </form>
            {% endblock search_bar %}
        </div>
        {% include 'partials/nav.html' %}

    </header>
    {% block content %}{% endblock content %}
    {% include 'partials/footer.html' %}

    <script>
        const langSelect = document.getElementById("js-lang");
        const handleLangChange = () => {
            const selected = langSelect.value;
            fetch(`{% url 'users:switch-language' %}?lang=${selected}`).then(() => window.location.reload());
        }
        langSelect.addEventListener("change", handleLangChange);
    </script>
</body>

</html>

templates/update_done.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static  'css/styles.css' %}">
</head>

<body class="bg-gray-500">
    <div class="container mx-auto w-full h-screen bg-gray-500 flex justify-center items-center flex-col p-0">
        <span class="text-yellow-500 font-light text-3xl mb-8">변경 완료!</span>

        <span class="text-yellow-500 font-light text-3xl">창을 닫고 새로고침하세요.</span>
    </div>
</body>