config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# settings.py 를 직접 import 하는 게 아니라 장고 시스템에서 conf 에 clone 된 settings 를 import.


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # DEBUG 가 켜져있을 때 (developing 일 때)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# MEDIA_URL 로 접근했을 때 어느 경로를 참조할 것인지

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
    path("my-list/", views.MyReservationsView.as_view(), name="my-list"),
    path(
        "room-reservation/<int:room_pk>/",
        views.RoomReservationView.as_view(),
        name="room-reservation",
    ),
]

reservations/models.py
import datetime
from django.db import models
from core import models as core_models
from django.utils import timezone
from . import managers


class BookedDay(core_models.TimeStampedModel):

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Day"

    def __str__(self):

        return str(self.day)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    class Meta:
        ordering = ("-created",)

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField(blank=True, null=True, default=0)
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE
    )
    objects = managers.CustomReservationManager()

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True  # Admin 패널에서 반환값을 기호로(아이콘으로) 바꿔줌.

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def clean(self):  # Seed 때문에 만듬. save 에서 호출.
        if not self.check_out:
            self.check_out = self.check_in + datetime.timedelta(days=1)

    def save(self, *args, **kwargs):
        self.clean()
        # if self.pk is None:
        try:
            kwargs["edit"]
            return super().save()
        except KeyError:
            if True:
                start = self.check_in
                end = self.check_out
                difference = end - start
                existing_booked_day = BookedDay.objects.filter(
                    day__range=(start, start + datetime.timedelta(days=1)),
                    reservation__room=self.room,
                )
                if not existing_booked_day.exists():
                    super().save(*args, **kwargs)
                    for i in range(difference.days + 1):
                        day = start + datetime.timedelta(days=i)
                        BookedDay.objects.create(day=day, reservation=self)
                elif len(existing_booked_day) == 1:
                    super().save(*args, **kwargs)
                    BookedDay.objects.create(day=start, reservation=self)

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View, TemplateView
from django.contrib import messages
from django.shortcuts import redirect, reverse, render
from django.urls import NoReverseMatch
from rooms import models as room_models
from reviews import forms as review_forms
from users.mixins import LoggedInOnlyView
from . import models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):

    try:
        date_obj = datetime.datetime(year=year, month=month, day=day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()

    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "예약할 수 없습니다.")
        return redirect(reverse("core:home"))

    except models.BookedDay.DoesNotExist:

        if request.user.is_anonymous:
            messages.error(request, "로그인 후 이용하세요.")
            return redirect(reverse("users:login"))
        elif request.user == room.host:
            messages.error(request, "잘못된 접근입니다.")
            return redirect(reverse("core:home"))

        reservation = models.Reservation.objects.create(
            guest=request.user, room=room, check_in=date_obj
        )
        messages.warning(request, "예약 완료! 감사합니다")
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation:
            messages.error(self.request, "잘못된 접근입니다.")
            return redirect(reverse("core:home"))

        if (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()

        form = review_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation, "form": form},
        )


class RoomReservationView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("room_pk")
        room = room_models.Room.objects.get_or_none(pk=pk)
        if not room:
            messages.error(self.request, "잘못된 접근입니다.")
            return redirect(reverse("core:home"))

        if room.host != self.request.user:
            messages.error(self.request, "잘못된 접근입니다.")
            return redirect(reverse("core:home"))

        return render(
            self.request, "reservations/room_reservation.html", {"room": room}
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation:
        messages.error(request, "잘못된 접근입니다.")
        return redirect(reverse("core:home"))

    if reservation.guest != request.user and reservation.room.host != request.user:
        raise Http404()

    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
        messages.warning(request, "승인 완료!")
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
        messages.error(request, "예약 취소되었습니다.")

    reservation.save(edit=True)
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class MyReservationsView(LoggedInOnlyView, TemplateView):

    template_name = "reservations/my_reservation_list.html"

templates/reservations/detail.html
{% extends 'base.html' %}


{% block page_title %}
{{reservation.room}} Reservation: {{reservation.check_in}}
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}


{% block content %}
<div class="container mx-auto my-10 flex flex-col px-20">
    <div class="bg-cover bg-center h-60 rounded-t-lg mt-12"
        style="background-image: url({{reservation.room.first_photo}});">
    </div>
    <div class="py-12 px-5 flex flex-col">
        <div class="border-b border-gray-400 py-5">
            {{reservation.check_in}} - {{reservation.check_out}} <span
                class="{% if reservation.status == 'pending' %}text-blue-600{% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-green-500 {% endif %}">{{reservation.get_status_display}}</span>
        </div>
        <div class="flex py-8 items-center border-b border-gray-400 justify-between">
            <div class="flex">
                <div class="flex flex-col items-center justify-center">
                    {% include 'mixins/link_removed_user_avatar.html' with user_obj=reservation.room.host %}
                    <span class="mt-2 font-light text-gray-500">{{reservation.room.host.first_name}}</span>
                </div>
                <div class="flex flex-col justify-center items-start pl-8">
                    <span class="text-xl">
                        {{reservation.room.name}}
                    </span>
                    {% if reservation.room.host != user %}
                    <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk%}"
                        class="text-lg text-blue-400 py-3">호스트에게 연락하기</a>
                    {% endif %}
                </div>
            </div>
            <div class="flex justify-end my-8 items-center">

                {% if reservation.status == 'pending' %}
                {% if reservation.room.host == user %}
                <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}"
                    class="font-light text-2xl ml-8 text-gray-100 rounded-md bg-blue-400 p-3">예약 승인</a>
                <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}"
                    class="font-light text-2xl ml-8 text-gray-100 rounded-md bg-gray-400 p-3">예약 거절</a>
                {% else %}
                <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}"
                    class="font-light text-2xl ml-8 text-gray-100 rounded-md bg-gray-400 p-3 w-32 text-center">예약 취소</a>
                <a href="{% url 'rooms:detail' reservation.room.pk %}"
                    class="font-light text-2xl ml-8 text-gray-100 rounded-md bg-blue-400 p-3 w-32 text-center">돌아가기</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="mt-10">
            {% if reservation.status == 'confirmed' and reservation.is_finished and user != reservation.room.host %}
            <div class="flex justify-center items-center">
                <span class="font-light text-3xl mb-6 block">리뷰 작성하기</span>
            </div>
            <div class="flex justify-center">
                <div class="w-3/5">
                    {% include 'mixins/auth/review_form.html' with form=form cta="리뷰 등록" %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/reservations/my_reservation_list.html
{% extends 'base.html' %}

{% block page_title %}
{{user.first_name}}'s Reservation
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}


{% block content %}
{% if user.reservations.all %}
<div class="container mx-auto my-40 flex flex-col items-center border-white border-4 p-6 lg:w-5/12 md:w-1/2 rounded-lg">
    <span class="flex w-full justify-center text-blue-600 text-3xl font-light mb-8 mt-3">내 예약</span>
    {% for reservation in user.reservations.all %}
    <div class="py-6 border-gray-400 border-b w-full flex justify-between">
        <a href="{% url 'reservations:detail' reservation.pk %}"><span>{{reservation}}</span></a>
        <span
            class="{% if reservation.status == 'pending' %} text-blue-600 {% elif reservation.status == 'confirmed' %} text-green-600 {% else %} text-red-600 {% endif %}">{{reservation.status}}</span>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container mx-auto my-40 flex flex-col items-center border-white border-4 p-6 lg:w-5/12 md:w-1/2 rounded-lg">
    <span class="flex w-full justify-center text-blue-600 text-3xl font-light">예약이 없습니다</span>
</div>
{% endif %}
{% endblock content %}

templates/reservations/reservation_list.html
{% extends 'base.html' %}

{% block page_title %}
{{user.first_name}}'s Reservation
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}


{% block content %}
{% if user.reservations.all %}
<div class="container mx-auto my-40 flex flex-col items-center border-white border-4 p-6 lg:w-5/12 md:w-1/2 rounded-lg">
    <span class="flex w-full justify-center text-blue-600 text-3xl font-light mb-8 mt-3">내 예약</span>
    {% for reservation in user.reservations.all %}
    <div class="py-6 border-gray-400 border-b w-full flex justify-between">
        <a href="{% url 'reservations:detail' reservation.pk %}"><span>{{reservation}}</span></a>
        <span
            class="{% if reservation.status == 'pending' %} text-blue-600 {% elif reservation.status == 'confirmed' %} text-green-600 {% else %} text-red-600 {% endif %}">{{reservation.status}}</span>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container mx-auto my-40 flex flex-col items-center border-white border-4 p-6 lg:w-5/12 md:w-1/2 rounded-lg">
    <span class="flex w-full justify-center text-blue-600 text-3xl font-light mb-8 mt-3">예약이 없습니다</span>
</div>
{% endif %}
{% endblock content %}

templates/reservations/room_reservation.html
{% extends 'base.html' %}

{% block page_title %}
Reservation of {{room.name}}
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}


{% block content %}
{% if room.reservations.all %}
<div class="container mx-auto my-40 flex flex-col items-center border-white border-4 p-6 lg:w-5/12 md:w-1/2 rounded-lg">
    <span class="flex w-full justify-center text-blue-600 text-3xl mb-10 mt-5">{{room.name}} 의 예약</span>
    {% for reservation in room.reservations.all %}
    <div class="py-6 border-gray-400 border-b w-full flex justify-between">
        <a href="{% url 'reservations:detail' reservation.pk %}"><span>{{reservation}}</span></a>
        <span
            class="{% if reservation.status == 'pending' %} text-blue-600 {% elif reservation.status == 'confirmed' %} text-green-600 {% else %} text-red-600 {% endif %}">{{reservation.status}}</span>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container mx-auto my-40 flex flex-col items-center border-white border-4 p-6 lg:w-5/12 md:w-1/2 rounded-lg">
    <span class="flex w-full justify-center text-blue-600 text-3xl font-light">{{room.name}} 의 예약이 없습니다</span>
</div>
{% endif %}
{% endblock content %}